### ISSUE TITLE
Bug thing

### ISSUE THREAD

**Issue by yavko** [hyperupcall/bpm#75]
Happens when i source my zshrc
<img width="1050" alt="CleanShot 2021-08-21 at 20 34 44@2x" src="https://user-images.githubusercontent.com/15178513/130341145-dfc93928-3bab-49d3-880b-ad7a0118113c.png">
macOS, zsh 5.8, and GNU bash, version 5.1.4

**Comment by hyperupcall** [comment]
Thank you for the report! :) I am investigating this bug

**Comment by hyperupcall** [comment]
@yavko Okai, it should be fixed now! The error was due to the fact that `bpm-load` was both an executable and a shell function (and sourcing a shell function makes no sense). For some reason, I didn't anticipate this error seriously

Is the issue fixed on your end as well by upgrading with `bpm upgrade bpm`?

**Comment by yavko** [comment]
ok

**Comment by yavko** [comment]
fixed sorry no response
